sudo: false
language: node_js
node_js:
    - stable
    - '0.12'
env:
   - NODE_ENV=development
install:
    - npm install
    - npm install mocha -g
script:
    - mocha
cache:
  directories:
    - node_modules
git:
  depth: 1
