language: node_js
sudo: false
cache:
  directories:
    - node_modules
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
  - '6'
  - '4'
  - '0.12'
env:
  - NODE_ENV=development
install:
  - npm install
  - npm install mocha -g
script:
  - mocha
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
